addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.6")
addSbtPlugin("com.codecommit" % "sbt-github-actions" % "0.14.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.2.2")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.10.0")
